version: "2"
services:
        osgtopoppusagereport:
                image: "shreyb/osg-reports:osgtopoppusagereport_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/osg-reports-config
                        - /etc/localtime:/etc/localtime
                network_mode: "host"
                command: ["-s", "${starttime}", "-e", "${endtime}", "-c", "/tmp/osg-reports-config/osg.toml", "-N", "${number}", "-T", "/tmp/html_templates/template_topoppusage.html"]
