version: "2"
services:
        osgpersitereport:
                image: "shreyb/osg-reports:osgpersitereport_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/gracc-config
                        - /etc/localtime:/etc/localtime
                network_mode: "host"
                command: ["-s", "${starttime}", "-c", "/tmp/gracc-config/osg.toml", "-L", "/tmp/log/osgpersitereport.log"]

