version: "2"
services:
        osgprojectreport:
                image: "shreyb/osg-reports:osgprojectreport_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/osg-reports-config
                        - /etc/localtime:/etc/localtime
                network_mode: "host"
                command: ["-s", "${starttime}", "-e", "${endtime}", "-c", "/tmp/osg-reports-config/osg.toml", "-r" ,"${TYPE}", "-T", "/tmp/html_templates/template_project.html"]

